events {}

http {
    server {
        listen 80;

        #  Auth Service 
        location /api/auth/ {
            proxy_pass http://auth-django:8001/api/auth/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        #  Event Service 
        location /api/events/ {
            proxy_pass http://event-django:8002/api/events/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        #  RSVP Service 
        location /api/rsvp/ {
            proxy_pass http://rsvp-django:8003/api/rsvp/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        #  Notification Service
        location /api/notifications/ {
            proxy_pass http://notif-django:8004/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        #  WebSocket
        location /ws/ {
            proxy_pass http://notif-asgi:8005;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $host;
            proxy_read_timeout 86400;
        }
    }
}