# Generated by Django 6.0.7 on 2026-07-28 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RSVP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('status', models.CharField(choices=[('joined', 'Joined'), ('cancelled', 'Cancelled')], default='joined', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('event_id', 'user_id')},
            },
        ),
    ]
